version: '3.3'
services:
  tema:
    container_name: tema
    build: .
    ports:
      - 6000:6000
    depends_on:
      - mongo
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: adrian
      MONGO_PORT: 27017
      MONGO_HOST: mongo
    networks:
      - server

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: adrian
    ports:
      - 27017:27017
    networks:
      - gui
      - server

  mongo-express:
    image: mongo-express
    container_name: monog-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: adrian
      ME_CONFIG_MONGODB_URL: mongodb://root:adrian@mongo:27017/
    networks:
      - gui

networks:
  server:
    name: server
  gui:
    name: gui